=== dymensionxyz/dymension/ibc_data.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "required": ["chain_1", "chain_2", "channels"],
  "properties": {
    "$schema": {
      "type": "string",
      "pattern": "^(\\.\\./)+ibc_data\\.schema\\.json$"
    },
    "chain_1": {
      "type": "object",
      "$ref": "#/$defs/chain_info"
    },
    "chain_2": {
      "type": "object",
      "$ref": "#/$defs/chain_info"
    },
    "channels": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["chain_1", "chain_2", "ordering", "version"],
        "properties": {
          "chain_1": {
            "type": "object",
            "$ref": "#/$defs/channel_info"
          },
          "chain_2": {
            "type": "object",
            "$ref": "#/$defs/channel_info"
          },
          "ordering": {
            "enum": ["ordered", "unordered"],
            "description": "Determines if packets from a sending module must be 'ordered' or 'unordered'."
          },
          "version": {
            "type": "string",
            "description": "IBC Version"
          },
          "description": {
            "type": "string",
            "description": "Human readable description of the channel."
          },
          "tags": {
            "type": "object",
            "description": "Human readable key:value pairs that help describe and distinguish channels.",
            "properties": {
              "status": {
                "enum": ["live", "upcoming", "killed"]
              },
              "preferred": {
                "type": "boolean"
              },
              "dex": {
                "type": "string"
              },
              "properties": {
                "type": "string",
                "description": "String that helps describe non-dex use cases ex: interchain accounts(ICA)."
              }
            },
            "additionalProperties": true
          }
        },
        "additionalProperties": false
      }
    },
    "operators": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["chain_1", "chain_2"],
        "properties": {
          "chain_1": {
            "type": "object",
            "$ref": "#/$defs/operator_info"
          },
          "chain_2": {
            "type": "object",
            "$ref": "#/$defs/operator_info"
          },
          "memo": {
            "type": "string",
            "description": "Relayer memo included in transactions"
          },
          "name": {
            "type": "string",
            "description": "Relayer name"
          },
          "discord": {
            "type": "object",
            "required": ["handle", "id"],
            "properties": {
              "handle": {
                "type": "string",
                "description": "Relayer discord handle"
              },
              "id": {
                "type": "string",
                "description": "Relayer discord ID"
              }
            }
          }
        }
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "chain_info": {
      "type": "object",
      "description": "Top level IBC data pertaining to the chain. `chain_1` and `chain_2` should be in alphabetical order.",
      "required": ["chain_name", "client_id", "connection_id"],
      "properties": {
        "chain_name": {
          "type": "string"
        },
        "client_id": {
          "type": "string",
          "description": "The client ID on the corresponding chain representing the other chain's light client."
        },
        "connection_id": {
          "type": "string",
          "description": "The connection ID on the corresponding chain representing a connection to the other chain."
        }
      },
      "additionalProperties": false
    },
    "channel_info": {
      "type": "object",
      "required": ["channel_id", "port_id"],
      "properties": {
        "channel_id": {
          "type": "string",
          "description": "The channel ID on the corresponding chain's connection representing a channel on the other chain."
        },
        "port_id": {
          "type": "string",
          "description": "The IBC port ID which a relevant module binds to on the corresponding chain."
        }
      },
      "additionalProperties": false
    },
    "operator_info": {
      "type": "object",
      "required": ["address"],
      "properties": {
        "address": {
          "type": "string",
          "description": "The signer address of the relayer operator"
        }
      }
    }
  }
}

=== dymensionxyz/dymension/_IBC/cosmoshub-dymension.json
{
  "$schema": "../ibc_data.schema.json",
  "chain_1": {
    "chain_name": "cosmoshub",
    "client_id": "07-tendermint-1205",
    "connection_id": "connection-933"
  },
  "chain_2": {
    "chain_name": "dymension",
    "client_id": "07-tendermint-1",
    "connection_id": "connection-1"
  },
  "channels": [
    {
      "chain_1": {
        "channel_id": "channel-794",
        "port_id": "transfer"
      },
      "chain_2": {
        "channel_id": "channel-1",
        "port_id": "transfer"
      },
      "ordering": "unordered",
      "version": "ics20-1",
      "tags": {
        "status": "live",
        "preferred": true
      }
    }
  ],
   "operators": [
    {
      "chain_1": {
        "address": "cosmos16f699curkzmvsfwn04qfr6u9es6yw7rhrq96nu"
      },
      "chain_2": {
        "address": "dym1nnxgtp6at89q4675edndcawwp9q7knhafe7xx7"
      },
      "memo": "Pro-Nodes75 Relayer",
      "name": "Pro-Nodes75",
      "discord": {
        "handle": "sw33pronodes",
        "id": "748273679711994028"
      }
    },
    {
      "chain_1": {
        "address": "cosmos1"
      },
      "chain_2": {
        "address": "dym1"
      },
      "memo": "",
      "name": "",
      "discord": {
        "handle": "",
        "id": ""
      }
    }
  ]
}

=== dymensionxyz/dymension/_IBC/celestia-dymension.json
{
  "$schema": "../ibc_data.schema.json",
  "chain_1": {
    "chain_name": "celestia",
    "client_id": "07-tendermint-82",
    "connection_id": "connection-52"
  },
  "chain_2": {
    "chain_name": "dymension",
    "client_id": "07-tendermint-6",
    "connection_id": "connection-5"
    
  },
  "channels": [
    {
      "chain_1": {
        "channel_id": "channel-27",
        "port_id": "transfer"
      },
      "chain_2": {
        "channel_id": "channel-4",
        "port_id": "transfer"
      },
      "ordering": "unordered",
      "version": "ics20-1",
      "tags": {
        "status": "live",
        "preferred": true
      }
    }
  ],
 "operators": [
    {
      "chain_1": {
        "address": "celestia1wvj4kuv4jnwc8v6mc6wsddrp3qvwmylpw72s99"
      },
      "chain_2": {
        "address": "dym1nnxgtp6at89q4675edndcawwp9q7knhafe7xx7"
      },
      "memo": "Pro-Nodes75 Relayer",
      "name": "Pro-Nodes75",
      "discord": {
        "handle": "sw33pronodes",
        "id": "748273679711994028"
      }
    },
    {
      "chain_1": {
        "address": "celestia1"
      },
      "chain_2": {
        "address": "dym1"
      },
      "memo": "",
      "name": "",
      "discord": {
        "handle": "",
        "id": ""
      }
    }
  ]
}

=== dymensionxyz/dymension/_IBC/archway-dymension.json
{
  "$schema": "../ibc_data.schema.json",
  "chain_1": {
    "chain_name": "archway",
    "client_id": "07-tendermint-91",
    "connection_id": "connection-89"
  },
  "chain_2": {
    "chain_name": "dymension",
    "client_id": "07-tendermint-39",
    "connection_id": "connection-30"
  },
  "channels": [
    {
      "chain_1": {
        "channel_id": "channel-123",
        "port_id": "transfer"
      },
      "chain_2": {
        "channel_id": "channel-45",
        "port_id": "transfer"
      },
      "ordering": "unordered",
      "version": "ics20-1",
      "tags": {
        "status": "live"
      }
    }
  ],
  "operators": [
    {
      "chain_1": {
        "address": "archway1dvfr02esfgkhwxrlv6x3dcq5cy58pcvyjam438"
      },
      "chain_2": {
        "address": "dym1nnxgtp6at89q4675edndcawwp9q7knhafe7xx7"
      },
      "memo": "Pro-Nodes75 Relayer",
      "name": "Pro-Nodes75",
      "discord": {
        "handle": "sw33pronodes",
        "id": "748273679711994028"
      }
    }
  ]
}

=== dymensionxyz/dymension/_IBC/dymension-noble.json
{
  "$schema": "../ibc_data.schema.json",
  "chain_1": {
    "chain_name": "dymension",
    "client_id": "07-tendermint-14",
    "connection_id": "connection-7"
  },
  "chain_2": {
    "chain_name": "noble",
    "client_id": "07-tendermint-79",
    "connection_id": "connection-80"
  },
  "channels": [
    {
      "chain_1": {
        "channel_id": "channel-6",
        "port_id": "transfer"
      },
      "chain_2": {
        "channel_id": "channel-62",
        "port_id": "transfer"
      },
      "ordering": "unordered",
      "version": "ics20-1",
      "tags": {
        "status": "live",
        "preferred": true
      }
    }
  ],
  "operators": [
    {
      "chain_1": {
        "address": "dym1nnxgtp6at89q4675edndcawwp9q7knhafe7xx7"
      },
      "chain_2": {
        "address": "noble15tmz024xrncl6n8kawzws6nzauua85pktjrepv"
      },
      "memo": "Pro-Nodes75 Relayer",
      "name": "Pro-Nodes75",
      "discord": {
        "handle": "sw33pronodes",
        "id": "748273679711994028"
      }
    },
    {
      "chain_1": {
        "address": "dym1"
      },
      "chain_2": {
        "address": "noble1"
      },
      "memo": "",
      "name": "",
      "discord": {
        "handle": "",
        "id": ""
      }
    }
  ]
}
